name: formux
version: 0.0.10
description: "Form validator system"
homepage: "https://formux.pipen.dev"
repository: "https://github.com/juanfelipepipen/formux"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter

  bloc: ^9.0.0
  intl: any
  pipen_bloc: any
  pipen: ^0.0.29
  email_validator: ^3.0.0
  flutter_skeleton_ui: ^0.0.6

#  pipen:
#    path: ../pipen-library
#  cloux:
#    path: ../cloux

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true