name: formux
version: 0.0.9
description: "Form validator system"
homepage: "https://formux.pipen.dev"
repository: "https://github.com/juanfelipepipen/formux"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter

  #  pipen: ^0.0.25
  pipen:
    path: ../pipen-library
  cloux:
    path: ../cloux
  intl: ^0.19.0
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
