name: formux
version: 0.0.8
description: "Form validator system"
homepage: "https://formux.pipen.dev"
repository: "https://github.com/juanfelipepipen/formux"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

  pipen:
    path: ../pipen-library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
