name: flutter_formux
version: 1.0.7
homepage: https://formux.pipen.dev
repository: https://github.com/juanfelipepipen/formux
documentation: https://formux.pipen.dev
topics: [formux, form, validations]
description: Interface tools for validating forms, managing state with BLoC, integrating with
  Material components.

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

  flutter_localizations:
    sdk: flutter

  bloc: ^9.0.0
  intl: ^0.20.0
  email_validator: ^3.0.0
  flutter_skeleton_ui: ^0.0.6
  currency_textfield: ^4.14.1

  # Pipen libs
  pipen: ^2.2.2
  formux: ^2.1.1
  pipen_bloc: ^1.2.4
  file_picker: ^10.2.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true