name: formux
version: 1.1.0
description: Form validator system
homepage: https://formux.pipen.dev
repository: https://github.com/juanfelipepipen/formux
documentation: https://formux.pipen.dev
topics: [form, validations]

environment:
  sdk: ^3.7.2

dependencies:
  email_validator: ^3.0.0

dev_dependencies:
