name: formux
version: 2.1.1
description: Form validator, input logging, dynamic error handling, integrable with running 
  components and applicable for UI with flutter_formux
homepage: https://formux.pipen.dev
documentation: https://formux.pipen.dev
repository: https://github.com/juanfelipepipen/formux
topics: [form, validations]

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  email_validator: ^3.0.0
  bloc: ^9.0.0
  collection: ^1.19.1
